<a href="https://colab.research.google.com/github/SkyInformationTechnology/Bootcamp/blob/main/EDA_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/winequality-red - Copy.csv")

In [ ]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
df.sample()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1250,7.1,0.6,0.01,2.3,0.079,24.0,37.0,0.99514,3.4,0.61,10.9,6

In [ ]:
out = [ ]
def Zscore_outlier(df):
  m = np.mean(df)
  sd = np.std(df)
  for i in df :
    Z = (i-m)/sd
    if np.abs(Z)>3:
      out.append(i)
  print("outliers:",out)
  Zscore_outlier(df['fixed acidity'])