<a href="https://colab.research.google.com/github/SkyInformationTechnology/Bootcamp/blob/main/EDA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/IRIS.csv")

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.head(60)

    sepal_length  sepal_width  petal_length  petal_width          species
0            5.1          3.5           1.4          0.2      Iris-setosa
1            4.9          3.0           1.4          0.2      Iris-setosa
2            4.7          3.2           1.3          0.2      Iris-setosa
3            4.6          3.1           1.5          0.2      Iris-setosa
4            5.0          3.6           1.4          0.2      Iris-setosa
5            5.4          3.9           1.7          0.4      Iris-setosa
6            4.6          3.4           1.4          0.3      Iris-setosa
7            5.0          3.4           1.5          0.2      Iris-setosa
8            4.4          2.9           1.4          0.2      Iris-setosa
9            4.9          3.1           1.5          0.1      Iris-setosa
10           5.4          3.7           1.5          0.2      Iris-setosa
11           4.8          3.4           1.6          0.2      Iris-setosa
12           4.8          3.0           1.4          0.1      Iris-setosa
13           4.3          3.0           1.1          0.1      Iris-setosa
14           5.8          4.0           1.2          0.2      Iris-setosa
15           5.7          4.4           1.5          0.4      Iris-setosa
16           5.4          3.9           1.3          0.4      Iris-setosa
17           5.1          3.5           1.4          0.3      Iris-setosa
18           5.7          3.8           1.7          0.3      Iris-setosa
19           5.1          3.8           1.5          0.3      Iris-setosa
20           5.4          3.4           1.7          0.2      Iris-setosa
21           5.1          3.7           1.5          0.4      Iris-setosa
22           4.6          3.6           1.0          0.2      Iris-setosa
23           5.1          3.3           1.7          0.5      Iris-setosa
24           4.8          3.4           1.9          0.2      Iris-setosa
25           5.0          3.0           1.6          0.2      Iris-setosa
26           5.0          3.4           1.6          0.4      Iris-setosa
27           5.2          3.5           1.5          0.2      Iris-setosa
28           5.2          3.4           1.4          0.2      Iris-setosa
29           4.7          3.2           1.6          0.2      Iris-setosa
30           4.8          3.1           1.6          0.2      Iris-setosa
31           5.4          3.4           1.5          0.4      Iris-setosa
32           5.2          4.1           1.5          0.1      Iris-setosa
33           5.5          4.2           1.4          0.2      Iris-setosa
34           4.9          3.1           1.5          0.1      Iris-setosa
35           5.0          3.2           1.2          0.2      Iris-setosa
36           5.5          3.5           1.3          0.2      Iris-setosa
37           4.9          3.1           1.5          0.1      Iris-setosa
38           4.4          3.0           1.3          0.2      Iris-setosa
39           5.1          3.4           1.5          0.2      Iris-setosa
40           5.0          3.5           1.3          0.3      Iris-setosa
41           4.5          2.3           1.3          0.3      Iris-setosa
42           4.4          3.2           1.3          0.2      Iris-setosa
43           5.0          3.5           1.6          0.6      Iris-setosa
44           5.1          3.8           1.9          0.4      Iris-setosa
45           4.8          3.0           1.4          0.3      Iris-setosa
46           5.1          3.8           1.6          0.2      Iris-setosa
47           4.6          3.2           1.4          0.2      Iris-setosa
48           5.3          3.7           1.5          0.2      Iris-setosa
49           5.0          3.3           1.4          0.2      Iris-setosa
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor
55           5.7          2.8           4.5          1.3  Iris-versicolor
56           6.3          3.3           4.7          1.6  Iris-versicolor
57           4.9          2.4           3.3          1.0  Iris-versicolor
58           6.6          2.9           4.6          1.3  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor

In [ ]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# **Chaking messing value**

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64